language: go

env:
  - GO111MODULE=on GOFLAGS='-mod vendor'

git:
  depth: 1

install: true
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -v -race -cover ./...  # Run all the tests with the race detector enabled

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT