version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    ports:
      - 8081:8081




