version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  registry:
    image: boskiv/cargo-registry:0.2.3
    environment:
      STORAGE_TYPE: local
      MONGODB_URI: mongodb://mongo:27017
      GIT_REPO_URL: https://gitlab.rnd.wargaming.net/git-cargo/index.git
      GIT_REPO_USERNAME: git-cargo
      GIT_REPO_EMAIL: git-cargo@wargaming.net
      GIT_REPO_PASSWORD: User1234
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - gogs
  gogs:
    image: gogs/gogs
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gogs
      - DB_USER=gogs
      - DB_PASSWD=gogs
    ports:
      - "3000:3000"
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=gogs
      - POSTGRES_PASSWORD=gogs
      - POSTGRES_DB=gogs


